export const XML = 'xml';
export const SQL = 'sql';

export const TAB_NAME_TODOS = 'Завдання';
export const TAB_NAME_CATEGORIES = 'Категорії';

export const EVENT_KEY_TODOS = 'todos';
export const EVENT_KEY_CATEGORIES = 'categories';

export const INPUT_FIELD_IS_REQUIRED = 'Це поле обов\'язкове!';
export const SELECT_CATEGORY_IS_REQUIRED = 'Оберіть категорію!';

export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';

export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';

export const CHANGE_PROGRESS_REQUEST = 'CHANGE_PROGRESS_REQUEST';
export const CHANGE_PROGRESS_SUCCESS = 'CHANGE_PROGRESS_SUCCESS';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';

export const SWITCH_STORAGE_TYPE = 'SWITCH_STORAGE_TYPE';

export const ACTION_FAILURE = 'ACTION_FAILURE';
